import { sheets, sheetsAuthClient, sheetsWrite } from './sheets';

const TAB='JOBS';
const HEAD=['numero','drive_id','documento','spreadsheet_id','next_page','total_pages','status','updated_at'];
let controlIdCache:string|undefined,jobsLoaded=false,nextRow=2;
const jobRows=new Map<string,number>();const jobCache=new Map<string,NDJob>();
function controlId(){const id=process.env.ND_CONTROL_SPREADSHEET_ID?.trim();if(!id)throw new Error('Falta ND_CONTROL_SPREADSHEET_ID. Debe apuntar al Spreadsheet maestro de control, no a los datos de un PDF.');return id;}
async function controlSheetId(){if(controlIdCache)return controlIdCache;const id=controlId();const meta=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const have=new Set((meta.data.sheets||[]).map(s=>s.properties?.title));if(!have.has(TAB))await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests:[{addSheet:{properties:{title:TAB}}}]}});await sheetsWrite(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:`${TAB}!A1:H1`,valueInputOption:'RAW',requestBody:{values:[HEAD]}}));controlIdCache=id;return id;}
export interface NDJob{numero?:number;driveId:string;name:string;spreadsheetId?:string;nextPage:number;totalPages:number;status:string;}
async function loadJobs(){if(jobsLoaded)return;const id=await controlSheetId();const r=await sheets.spreadsheets.values.get({spreadsheetId:id,range:`${TAB}!A2:H`});const rows=r.data.values||[];nextRow=rows.length+2;rows.forEach((row,index)=>{const driveId=String(row[1]||'');if(!driveId)return;const job:NDJob={numero:Number(row[0]||0)||undefined,driveId,name:String(row[2]||''),spreadsheetId:row[3]||undefined,nextPage:Number(row[4]||1),totalPages:Number(row[5]||0),status:String(row[6]||'pendiente')};jobRows.set(driveId,index+2);jobCache.set(driveId,job);});jobsLoaded=true;}
export async function getJob(driveId:string,name:string,numero?:number):Promise<NDJob>{await loadJobs();const job=jobCache.get(driveId);if(!job){const fresh={numero,driveId,name,nextPage:1,totalPages:0,status:'pendiente'};jobCache.set(driveId,fresh);return fresh;}return {...job,name:job.name||name,numero:job.numero||numero};}
export async function saveJob(job:NDJob){await loadJobs();const id=await controlSheetId();const row=jobRows.get(job.driveId);const values=[[job.numero||'',job.driveId,job.name,job.spreadsheetId||'',job.nextPage,job.totalPages,job.status,new Date().toISOString()]];if(row)await sheetsWrite(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:`${TAB}!A${row}:H${row}`,valueInputOption:'RAW',requestBody:{values}}));else{const targetRow=nextRow++;await sheetsWrite(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:`${TAB}!A${targetRow}:H${targetRow}`,valueInputOption:'RAW',requestBody:{values}}));jobRows.set(job.driveId,targetRow);}jobCache.set(job.driveId,{...job});}
