import { google } from 'googleapis';
import fs from 'node:fs';
import { getOrCreateSheet } from './sheets';
const TAB='JOBS';
const HEAD=['drive_id','documento','spreadsheet_id','next_page','total_pages','status','updated_at'];
let controlIdCache:string|undefined,jobsLoaded=false,nextRow=2;
const jobRows=new Map<string,number>();const jobCache=new Map<string,NDJob>();let lastWrite=0;
function getAuth(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON?.trim();if(raw){const c=JSON.parse(raw);return new google.auth.GoogleAuth({credentials:{client_email:c.client_email,private_key:c.private_key},scopes:['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets']});}const p=process.env.GOOGLE_CREDENTIALS_PATH?.trim();if(!p)throw new Error('Falta GOOGLE_SERVICE_ACCOUNT_JSON o GOOGLE_CREDENTIALS_PATH');if(!fs.existsSync(p))throw new Error(`No existe GOOGLE_CREDENTIALS_PATH: ${p}`);const c=JSON.parse(fs.readFileSync(p,'utf8'));return new google.auth.GoogleAuth({credentials:{client_email:c.client_email,private_key:c.private_key},scopes:['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets']});}
const auth=getAuth();const sheets=google.sheets({version:'v4',auth});
async function write<T>(fn:()=>Promise<T>):Promise<T>{const w=Math.max(0,1100-(Date.now()-lastWrite));if(w)await new Promise(r=>setTimeout(r,w));const x=await fn();lastWrite=Date.now();return x;}
async function controlSheetId(){if(controlIdCache)return controlIdCache;const id=await getOrCreateSheet('CONTROL','CONTROL');const meta=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const have=new Set((meta.data.sheets||[]).map(s=>s.properties?.title));if(!have.has(TAB))await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests:[{addSheet:{properties:{title:TAB}}}]}});await write(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:`${TAB}!A1:G1`,valueInputOption:'RAW',requestBody:{values:[HEAD]}}));controlIdCache=id;return id;}
export interface NDJob{driveId:string;name:string;spreadsheetId?:string;nextPage:number;totalPages:number;status:string;}
async function loadJobs(){if(jobsLoaded)return;const id=await controlSheetId();const r=await sheets.spreadsheets.values.get({spreadsheetId:id,range:`${TAB}!A2:G`});const rows=r.data.values||[];nextRow=rows.length+2;rows.forEach((row,index)=>{const driveId=String(row[0]||'');if(!driveId)return;const job:NDJob={driveId,name:String(row[1]||''),spreadsheetId:row[2]||undefined,nextPage:Number(row[3]||1),totalPages:Number(row[4]||0),status:String(row[5]||'pendiente')};jobRows.set(driveId,index+2);jobCache.set(driveId,job);});jobsLoaded=true;}
export async function getJob(driveId:string,name:string):Promise<NDJob>{await loadJobs();const job=jobCache.get(driveId);if(!job){const fresh={driveId,name,nextPage:1,totalPages:0,status:'pendiente'};jobCache.set(driveId,fresh);return fresh;}return {...job,name:job.name||name};}
export async function saveJob(job:NDJob){await loadJobs();const id=await controlSheetId();const row=jobRows.get(job.driveId);const values=[[job.driveId,job.name,job.spreadsheetId||'',job.nextPage,job.totalPages,job.status,new Date().toISOString()]];if(row)await write(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:`${TAB}!A${row}:G${row}`,valueInputOption:'RAW',requestBody:{values}}));else{const targetRow=nextRow++;await write(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:`${TAB}!A${targetRow}:G${targetRow}`,valueInputOption:'RAW',requestBody:{values}}));jobRows.set(job.driveId,targetRow);}jobCache.set(job.driveId,{...job});}
