import type { NDFinding } from './types';

export type KnowledgeRecord = { id:string; name:string; kind?:string; synonyms?:string[]; source:'supabase'|'turso'; raw?:Record<string,unknown> };
const norm=(s:string)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function assertSelect(sql:string){const q=sql.trim().replace(/^\(+|\)+$/g,'');if(!/^select\b/i.test(q)||/\b(insert|update|delete|drop|alter|create|truncate|replace|merge|grant|revoke|attach|detach|vacuum|pragma)\b/i.test(q))throw new Error('ND conocimiento: solo se permiten consultas SELECT de lectura.');}
async function supabaseRecords():Promise<KnowledgeRecord[]>{const base=process.env.ND_SUPABASE_URL?.trim()||process.env.SUPABASE_URL?.trim();const key=process.env.ND_SUPABASE_READ_KEY?.trim()||process.env.SUPABASE_KEY?.trim();const table=process.env.ND_SUPABASE_KNOWLEDGE_TABLE?.trim();if(!base||!key||!table)return [];if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(table))throw new Error('ND_SUPABASE_KNOWLEDGE_TABLE inválida');const url=`${base.replace(/\/$/,'')}/rest/v1/${table}?select=*`;const r=await fetch(url,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok)throw new Error(`Supabase lectura ND: HTTP ${r.status}`);const rows:any[]=await r.json();return rows.map((x:any):KnowledgeRecord=>({id:String(x.id??x.uuid??x.codigo??''),name:String(x.nombre??x.name??x.material??x.entidad??''),kind:String(x.kind??x.tipo??x.categoria??''),synonyms:Array.isArray(x.sinonimos)?x.sinonimos.map(String):[],source:'supabase',raw:x})).filter(x=>x.id&&x.name);}
async function tursoRecords():Promise<KnowledgeRecord[]>{const rawUrl=process.env.ND_TURSO_DATABASE_URL?.trim()||process.env.TURSO_DATABASE_URL?.trim();const token=process.env.ND_TURSO_READ_TOKEN?.trim()||process.env.TURSO_AUTH_TOKEN?.trim();const sql=process.env.ND_TURSO_KNOWLEDGE_SQL?.trim();if(!rawUrl||!token||!sql)return [];assertSelect(sql);const u=new URL(rawUrl.replace(/^libsql:/,'https:'));u.pathname='/v2/pipeline';const body={requests:[{type:'execute',stmt:{sql,args:[]}}]};const r=await fetch(u,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Turso lectura ND: HTTP ${r.status}`);const data:any=await r.json();const result=data.results?.[0]?.response?.result;const cols=(result?.cols||[]).map((c:any)=>c.name);const rows=result?.rows||[];return rows.map((row:any[]):KnowledgeRecord=>{const x:any={};cols.forEach((c:string,i:number)=>x[c]=row[i]?.value??row[i]);return {id:String(x.id??x.uuid??x.codigo??''),name:String(x.nombre??x.name??x.material??x.entidad??''),kind:String(x.kind??x.tipo??x.categoria??''),synonyms:Array.isArray(x.sinonimos)?x.sinonimos.map(String):[],source:'turso',raw:x};}).filter(x=>x.id&&x.name);}
export async function loadKnowledge():Promise<KnowledgeRecord[]>{const [s,t]=await Promise.all([supabaseRecords(),tursoRecords()]);const out:KnowledgeRecord[]=[];const seen=new Set<string>();for(const x of [...s,...t]){const k=`${x.source}:${x.id}`;if(!seen.has(k)){seen.add(k);out.push(x);}}return out;}
export function matchKnowledge(f:NDFinding,records:KnowledgeRecord[]):KnowledgeRecord|undefined{if(!records.length)return undefined;const candidates=[f.entity,f.normalizedText,f.field,f.documentaryData].map(norm).filter(Boolean);return records.find(r=>candidates.includes(norm(r.name))||r.synonyms?.some(s=>candidates.includes(norm(s))));}
export function knowledgeMetadata(f:NDFinding,records:KnowledgeRecord[]){const m=matchKnowledge(f,records);return m?{knowledgeId:m.id,knowledgeName:m.name,knowledgeKind:m.kind||'',knowledgeSource:m.source,knowledgeMatch:'exact_or_synonym'}:{knowledgeMatch:'not_found'};}
