import type { NDFinding } from './types';
import { knowledgeMetadata, type KnowledgeRecord } from './knowledge';
export type NDCoordinate={id:string;neuron:string;page:number;section:string;kind:string;entity:string;knowledgeId:string;path:string};
export type NDMemory={documentId:string;documentName:string;neuron:string;pages:Set<number>;findings:number;coordinates:NDCoordinate[]};
const norm=(s:string)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
function microNeuron(f:NDFinding){const source=String(f.metadata?.source||'');const rule=String(f.metadata?.rule||'');if(f.kind==='MAGNITUD'||f.kind==='FORMULA')return'micro-numerica';if(f.kind==='NORMA')return'micro-normativa';if(['MATERIAL','COMPONENTE','PROPIEDAD','ATRIBUTO'].includes(f.kind))return'micro-entidad';if(['RELACION','COMPORTAMIENTO','COMPOSICION'].includes(rule.toUpperCase())||f.kind==='RELACION')return'micro-relaciones';if(['CONDICION','METODO','INSTRUMENTO','APLICACION'].includes(f.kind))return'micro-contexto';if(source.includes('semantic'))return'micro-semantica';return'micro-evidencia';}
function confidenceBoost(f:NDFinding,meta:Record<string,unknown>){let c=Number(f.confidence||0);if(meta.knowledgeId)c=Math.min(1,c+.04);if(f.evidence?.fragment&&f.page>0)c=Math.min(1,c+.01);return Number(c.toFixed(4));}
export function createMemory(documentId:string,documentName:string,neuron:string):NDMemory{return{documentId,documentName,neuron,pages:new Set(),findings:0,coordinates:[]};}
export function processNeuralChunk(findings:NDFinding[],memory:NDMemory,knowledge:KnowledgeRecord[],fallbackPage:number,neuron:string){const out:NDFinding[]=[];for(const original of findings){const f:NDFinding={...original,metadata:{...(original.metadata||{})}};const page=Number(f.page||fallbackPage);const km=knowledgeMetadata(f,knowledge);const micro=microNeuron(f);const knowledgeId=String((km as any).knowledgeId||'');const section=String(f.section||'').trim();const entity=String(f.entity||f.field||'').trim();const seed=[memory.documentId,neuron,page,section,f.kind,entity,f.originalText].join('|');const coordId=`${neuron}:${page}:${hash(seed)}`;const coordPath=[neuron,`p${page}`,section||'sin_seccion',f.kind,knowledgeId||norm(entity)||'sin_entidad'].map(x=>x.replace(/[^\w.-]+/g,'_')).join('/');f.confidence=confidenceBoost(f,km as any);f.metadata={...f.metadata,...km,microNeuron:micro,coordinateId:coordId,coordinatePath:coordPath,memoryScope:memory.documentId,neuronId:neuron};f.evidence={...f.evidence,section:f.evidence.section||section};memory.pages.add(page);memory.findings++;memory.coordinates.push({id:coordId,neuron,page,section,kind:f.kind,entity,knowledgeId,path:coordPath});out.push(f);}return out;}
export function compressMemory(memory:NDMemory){const byKind:Record<string,number>={},byPage:Record<string,number>={};for(const c of memory.coordinates){byKind[c.kind]=(byKind[c.kind]||0)+1;byPage[String(c.page)]=(byPage[String(c.page)]||0)+1;}return{documentId:memory.documentId,documentName:memory.documentName,neuron:memory.neuron,pages:[...memory.pages].sort((a,b)=>a-b),findings:memory.findings,coordinates:memory.coordinates,summary:{byKind,byPage}};}
