import { google } from 'googleapis';
import fs from 'node:fs';
import type { NDMemory } from './neural';
import type { NDFinding } from './types';

function auth(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON?.trim();const p=process.env.GOOGLE_CREDENTIALS_PATH?.trim();const c=raw?JSON.parse(raw):p?JSON.parse(fs.readFileSync(p,'utf8')):null;if(!c)throw new Error('Falta credencial Google para mapa ND');return new google.auth.GoogleAuth({credentials:{client_email:c.client_email,private_key:c.private_key},scopes:['https://www.googleapis.com/auth/spreadsheets']});}
const sheets=google.sheets({version:'v4',auth:auth()});let ensured=false;let lastWrite=0;const WRITE_GAP_MS=1_100;
function quota(e:any){return /quota|rate.?limit|resource.?exhausted|429|too many requests/i.test(String(e?.message||e?.response?.data?.error?.message||e))}
async function write<T>(fn:()=>Promise<T>):Promise<T>{let d=0;for(let a=1;a<=8;a++){const w=Math.max(0,WRITE_GAP_MS-(Date.now()-lastWrite));if(w)await new Promise(r=>setTimeout(r,w));try{const x=await fn();lastWrite=Date.now();return x;}catch(e){if(!quota(e)||a===8)throw e;d=d?Math.min(d*2,60_000):2_000;await new Promise(r=>setTimeout(r,d+Math.floor(Math.random()*750)));}}throw new Error('Sheets neural write retry exhausted')}
export async function ensureNeuralSheets(id:string){if(ensured)return;const m=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const have=new Set((m.data.sheets||[]).map(s=>s.properties?.title));const names=['MAPA_ND','COORDENADAS_ND','MEMORIA_ND'];const requests=names.filter(n=>!have.has(n)).map(title=>({addSheet:{properties:{title}}}));if(requests.length)await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests}});await sheets.spreadsheets.values.batchUpdate({spreadsheetId:id,requestBody:{valueInputOption:'RAW',data:[{range:'MAPA_ND!A1:H1',values:[['documento_drive_id','documento','neurona','paginas','hallazgos','coordenadas','resumen_por_tipo','memoria_estado']]},{range:'COORDENADAS_ND!A1:I1',values:[['coordinate_id','documento_drive_id','neurona','pagina','seccion','tipo','entidad','knowledge_id','coordinate_path']]},{range:'MEMORIA_ND!A1:F1',values:[['documento_drive_id','documento','neurona','paginas','hallazgos','estado']]}]}});ensured=true;}
export async function appendNeuralChunk(id:string,m:NDMemory,findings:NDFinding[]){await ensureNeuralSheets(id);if(!findings.length)return;const byKind:Record<string,number>={};for(const f of findings)byKind[f.kind]=(byKind[f.kind]||0)+1;const coords=m.coordinates.slice(-findings.length);await write(()=>sheets.spreadsheets.values.append({spreadsheetId:id,range:'MAPA_ND!A1',valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:[[m.documentId,m.documentName,m.neuron,[...new Set(findings.map(f=>f.page))].sort((a,b)=>a-b).join(','),findings.length,coords.length,JSON.stringify(byKind),'incremental']]}}));if(coords.length){const rows=coords.map(c=>[c.id,m.documentId,m.neuron,c.page,c.section,c.kind,c.entity,c.knowledgeId,c.path]);await write(()=>sheets.spreadsheets.values.append({spreadsheetId:id,range:'COORDENADAS_ND!A1',valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:rows}}));}await write(()=>sheets.spreadsheets.values.append({spreadsheetId:id,range:'MEMORIA_ND!A1',valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:[[m.documentId,m.documentName,m.neuron,[...new Set(findings.map(f=>f.page))].sort((a,b)=>a-b).join(','),findings.length,'guardada']]}}));}
export async function appendNeuralMemory(id:string,m:NDMemory){await ensureNeuralSheets(id);const compact:any={};for(const c of m.coordinates)compact[c.kind]=(compact[c.kind]||0)+1;await write(()=>sheets.spreadsheets.values.append({spreadsheetId:id,range:'MAPA_ND!A1',valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:[[m.documentId,m.documentName,m.neuron,[...m.pages].sort((a,b)=>a-b).join(','),m.findings,m.coordinates.length,JSON.stringify(compact),'cerrada']]}}));}
