import { google } from 'googleapis';
import type { NDFinding } from './types';

const TABS=['DOCUMENTO','HALLAZGOS_RAW','MATERIALES','COMPONENTES','PROPIEDADES','MAGNITUDES','ATRIBUTOS','RELACIONES','CONDICIONES','METODOS','INSTRUMENTOS','APLICACIONES','COMPORTAMIENTOS','NORMAS','DEFINICIONES','EVIDENCIAS','FORMULAS','ENTIDADES_DOCUMENTALES'];
const HEAD=['drive_id','documento','tipo','campo','entidad','aspecto','dato_documental','texto_original','texto_normalizado','valor','valor_texto','unidad','simbolo','contexto','pagina','seccion','confianza','evidencia_json','metadatos_json'];
function getAuth(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Falta GOOGLE_SERVICE_ACCOUNT_JSON');const c=JSON.parse(raw);return new google.auth.GoogleAuth({credentials:{client_email:c.client_email,private_key:c.private_key},scopes:['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets']});}
const auth=getAuth();const sheets=google.sheets({version:'v4',auth});const drive=google.drive({version:'v3',auth});
function rows(doc:string,id:string,findings:NDFinding[]){return findings.map(h=>[id,doc,h.kind,h.field,h.entity,h.aspect,h.documentaryData,h.originalText,h.normalizedText,h.value??'',h.valueText??'',h.unit??'',h.symbol??'',h.context,h.page,h.section??'',h.confidence,JSON.stringify(h.evidence),JSON.stringify(h.metadata||{})]);}
async function ensure(id:string){const m=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const have=new Set((m.data.sheets||[]).map(s=>s.properties?.title));const requests=TABS.filter(t=>!have.has(t)).map(t=>({addSheet:{properties:{title:t}}}));if(requests.length)await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests}});const data:any[]=[];for(const t of TABS){const r=await sheets.spreadsheets.values.get({spreadsheetId:id,range:`${t}!A1:S1`});if(!r.data.values?.length)data.push({range:`${t}!A1`,values:[t==='DOCUMENTO'?['drive_id','documento','estado','hallazgos_total']:HEAD]});}if(data.length)await sheets.spreadsheets.values.batchUpdate({spreadsheetId:id,requestBody:{valueInputOption:'RAW',data}});}
export async function getOrCreateSheet(driveId:string,name:string){const parent=process.env.ND_SHEETS_FOLDER_ID;if(!parent)throw new Error('Falta ND_SHEETS_FOLDER_ID');const safe=`ARKON_ND_${name.replace(/[^\w.-]+/g,'_').slice(0,70)}`;const q=`'${parent}' in parents and name='${safe.replace(/'/g,"\\'")}' and mimeType='application/vnd.google-apps.spreadsheet' and trashed=false`;const found=await drive.files.list({q,fields:'files(id)',pageSize:1});let id=found.data.files?.[0]?.id;if(!id){const r=await drive.files.create({requestBody:{name:safe,mimeType:'application/vnd.google-apps.spreadsheet',parents:[parent]},fields:'id'});id=r.data.id!;}await ensure(id);return id;}
export async function appendFindings(id:string,driveId:string,name:string,findings:NDFinding[]){if(!findings.length)return;const all=rows(name,driveId,findings);for(let i=0;i<all.length;i+=500){await sheets.spreadsheets.values.append({spreadsheetId:id,range:'HALLAZGOS_RAW!A:S',valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:all.slice(i,i+500)}});}
 const map:any={MATERIAL:'MATERIALES',COMPONENTE:'COMPONENTES',PROPIEDAD:'PROPIEDADES',MAGNITUD:'MAGNITUDES',ATRIBUTO:'ATRIBUTOS',RELACION:'RELACIONES',CONDICION:'CONDICIONES',METODO:'METODOS',INSTRUMENTO:'INSTRUMENTOS',APLICACION:'APLICACIONES',COMPORTAMIENTO:'COMPORTAMIENTOS',NORMA:'NORMAS',DEFINICION:'DEFINICIONES',EVIDENCIA:'EVIDENCIAS',FORMULA:'FORMULAS',ENTIDAD:'ENTIDADES_DOCUMENTALES'};
 for(const [kind,tab] of Object.entries(map)){const rs=findings.filter(x=>x.kind===kind);const rr=rows(name,driveId,rs);for(let i=0;i<rr.length;i+=500)await sheets.spreadsheets.values.append({spreadsheetId:id,range:`${tab}!A:S`,valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:rr.slice(i,i+500)}});}
}
export async function setDocumentStatus(id:string,driveId:string,name:string,status:string,total:number){await sheets.spreadsheets.values.update({spreadsheetId:id,range:'DOCUMENTO!A2:D2',valueInputOption:'RAW',requestBody:{values:[[driveId,name,status,total]]}});}
