import { google } from 'googleapis';
import fs from 'node:fs';
import type { NDKind, NDFinding } from './types';

const TABS=['DOCUMENTO','PAGINAS','HALLAZGOS_RAW','MATERIALES','COMPONENTES','PROPIEDADES','MAGNITUDES','ATRIBUTOS','RELACIONES','CONDICIONES','METODOS','INSTRUMENTOS','APLICACIONES','COMPORTAMIENTOS','NORMAS','DEFINICIONES','EVIDENCIAS','FORMULAS','ENTIDADES_DOCUMENTALES','ND_TEXT_PARTES'];
const HEAD=['drive_id','documento','tipo','campo','entidad','aspecto','dato_documental','texto_original','texto_normalizado','valor','valor_texto','unidad','simbolo','contexto','pagina','seccion','confianza','evidencia_json','metadatos_json'];
const PAGE_HEAD=['drive_id','documento','pagina','parte','total_partes','texto_completo','bbox_json','words_json','blocks_json','headings_json','tables_json','links_json','images_json','ocr_usado'];
const TEXT_PART_HEAD=['drive_id','documento','origen','clave','campo','pagina','parte','total_partes','texto'];
const KIND_TO_TAB:Record<NDKind,string>={MATERIAL:'MATERIALES',COMPONENTE:'COMPONENTES',PROPIEDAD:'PROPIEDADES',MAGNITUD:'MAGNITUDES',ATRIBUTO:'ATRIBUTOS',RELACION:'RELACIONES',CONDICION:'CONDICIONES',METODO:'METODOS',INSTRUMENTO:'INSTRUMENTOS',APLICACION:'APLICACIONES',COMPORTAMIENTO:'COMPORTAMIENTOS',NORMA:'NORMAS',DEFINICION:'DEFINICIONES',EVIDENCIA:'EVIDENCIAS',FORMULA:'FORMULAS',ENTIDAD:'ENTIDADES_DOCUMENTALES'};
const CELL_LIMIT=45_000,WRITE_GAP_MS=1_100;
let lastWrite=0;const ensured=new Set<string>();
function sheetsAuth():any{
  const p=process.env.GOOGLE_SHEETS_CREDENTIALS_PATH?.trim();
  if(p){
    if(!fs.existsSync(p))throw new Error(`No existe GOOGLE_SHEETS_CREDENTIALS_PATH: ${p}`);
    const c=JSON.parse(fs.readFileSync(p,'utf8'));
    if(c.type==='service_account')throw new Error('ND requiere OAuth de usuario para crear Sheets en My Drive. No uses una credencial service_account para Sheets.');
    return google.auth.fromJSON(c) as any;
  }
  return new google.auth.GoogleAuth({scopes:['https://www.googleapis.com/auth/cloud-platform','https://www.googleapis.com/auth/spreadsheets']}) as any;
}
export const sheetsAuthClient:any=sheetsAuth();
export const sheets=google.sheets({version:'v4',auth:sheetsAuthClient as any});
export async function verifyUserSheetsAuth(){
  const creds:any=await (sheetsAuthClient as any).getCredentials();
  if(creds?.client_email)throw new Error(`La autenticación de Sheets está usando una cuenta de servicio (${creds.client_email}). Para crear un Spreadsheet por PDF en My Drive, autentica ADC como smcontenidos716@gmail.com.`);
}
function chunks(s:string){const out:string[]=[];for(let i=0;i<s.length;i+=CELL_LIMIT)out.push(s.slice(i,i+CELL_LIMIT));return out.length?out:[''];}
function json(v:any){try{return JSON.stringify(v??{})}catch{return '{}'}}
function isQuotaError(e:any){const s=String(e?.message||e?.response?.data?.error?.message||e);return /quota|rate.?limit|resource.?exhausted|429|too many requests/i.test(s)}
export async function sheetsWrite<T>(fn:()=>Promise<T>):Promise<T>{let delay=0;for(let attempt=1;attempt<=8;attempt++){const wait=Math.max(0,WRITE_GAP_MS-(Date.now()-lastWrite));if(wait)await new Promise(r=>setTimeout(r,wait));try{const r=await fn();lastWrite=Date.now();return r;}catch(e){if(!isQuotaError(e)||attempt===8)throw e;delay=delay?Math.min(delay*2,60_000):2_000;await new Promise(r=>setTimeout(r,delay+Math.floor(Math.random()*750)));}}throw new Error('Sheets write retry exhausted')}
async function appendBatch(id:string,range:string,values:any[][]){if(values.length)await sheetsWrite(()=>sheets.spreadsheets.values.append({spreadsheetId:id,range,valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values}}));}
function normalizeKind(kind:string):NDKind|''{const k=String(kind||'').trim().toUpperCase();const aliases:Record<string,NDKind>={PROPERTY:'PROPIEDAD',MAGNITUDE:'MAGNITUD',DEFINITION:'DEFINICION',COMPONENT:'COMPONENTE',RELATION:'RELACION',CONDITION:'CONDICION',REQUIREMENT:'CONDICION',METHOD:'METODO',INSTRUMENT:'INSTRUMENTO',APPLICATION:'APLICACION',BEHAVIOR:'COMPORTAMIENTO',STANDARD:'NORMA',NORM:'NORMA',FORMULA:'FORMULA',EVIDENCE:'EVIDENCIA',ATTRIBUTE:'ATRIBUTO',ENTITY:'ENTIDAD'};return KIND_TO_TAB[k as NDKind]?k as NDKind:aliases[k]||'';}
function rows(doc:string,id:string,findings:NDFinding[]){return findings.map(h=>[id,doc,h.kind,h.field,h.entity,h.aspect,h.documentaryData,h.originalText,h.normalizedText,h.value??'',h.valueText??'',h.unit??'',h.symbol??'',h.context,h.page,h.section??'',h.confidence,json(h.evidence),json(h.metadata||{})]);}
function unifiedRow(doc:string,h:NDFinding){const kind=normalizeKind(h.kind),m:any=h.metadata||{},ev:any=h.evidence||{},text=String(h.originalText||h.documentaryData||h.normalizedText||'').trim(),name=String(h.entity||h.field||h.normalizedText||text).trim();const cat=kind==='PROPIEDAD'?'Propiedad':kind==='MATERIAL'?'Material':kind==='COMPONENTE'?'Componente':kind==='METODO'?'Método':kind==='INSTRUMENTO'?'Instrumento':kind==='NORMA'?'Norma':kind==='CONDICION'?'Condición':kind==='RELACION'?'Relación':kind==='FORMULA'?'Fórmula':kind==='DEFINICION'?'Definición':kind==='APLICACION'?'Aplicación':kind==='COMPORTAMIENTO'?'Comportamiento':kind||h.kind||'';return [name,String(m.english||m.nombre_ingles||'').trim(),String(m.synonyms||m.sinonimos||'').trim()||'-',cat,String(h.aspect||m.property_type||m.tipo_propiedad||'-'),String(m.family||m.familia||'').trim()||'-',String(m.subfamily||m.subfamilia||'').trim()||'-',String(m.material||'').trim()||'-',String(m.component||m.componente||'').trim()||'-',h.unit||'',h.symbol||'',h.value??h.valueText??'',m.min??m.valor_min??'',m.max??m.valor_max??'',String(m.condition||m.condicion||'').trim(),String(m.method||m.metodo||'').trim(),String(m.instrument||m.instrumento||'').trim(),String(m.standard||m.norma||'').trim(),String(m.formula||m.equation||m.ecuacion||'').trim()||(kind==='FORMULA'?text:''),String(m.relation||m.relacion||'').trim(),h.confidence||'',String(m.origin||m.origen||'').trim()||'Tabla',doc,h.page??'',String(h.section||m.chapter||m.capitulo||'').trim()||'-',json({field:h.field,context:h.context,evidence:ev,metadata:m})];}
export async function ensure(id:string){if(ensured.has(id))return;const m=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const have=new Set((m.data.sheets||[]).map(s=>s.properties?.title));const req=TABS.filter(t=>!have.has(t)).map(title=>({addSheet:{properties:{title}}}));if(req.length)await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests:req}});const data=[{range:'DOCUMENTO!A1:D1',values:[['drive_id','documento','estado','hallazgos_total']]},{range:'PAGINAS!A1:N1',values:[PAGE_HEAD]},{range:'ND_TEXT_PARTES!A1:I1',values:[TEXT_PART_HEAD]},...TABS.filter(t=>!['DOCUMENTO','PAGINAS','ND_TEXT_PARTES'].includes(t)).map(t=>({range:`${t}!A1:S1`,values:[HEAD]}))];await sheets.spreadsheets.values.batchUpdate({spreadsheetId:id,requestBody:{valueInputOption:'RAW',data}});ensured.add(id);}
function safeTitle(s:string){return String(s).replace(/[/\\?*\[\]:]/g,'_').replace(/\s+/g,' ').trim().slice(0,150)||'PDF';}
export async function createPdfSpreadsheet(title:string){await verifyUserSheetsAuth();const r=await sheets.spreadsheets.create({requestBody:{properties:{title:safeTitle(title)}},fields:'spreadsheetId,spreadsheetUrl,properties.title'});const id=r.data.spreadsheetId;if(!id)throw new Error('Google Sheets no devolvió spreadsheetId al crear el archivo');await ensure(id);console.log(`ND | SPREADSHEET CREADO | ${r.data.properties?.title||title} | ${id} | ${r.data.spreadsheetUrl||`https://docs.google.com/spreadsheets/d/${id}/edit`}`);return id;}
export async function getOrCreateSheet(_driveId:string,_name:string){throw new Error('getOrCreateSheet ya no se usa: ND crea un Spreadsheet independiente por cada PDF.');}
export async function appendPages(id:string,driveId:string,name:string,pages:any[]){for(const p of pages){const row=[driveId,name,p.page,1,1,String(p.text||''),json(p.bbox||[]),json(p.words||[]),json(p.blocks||[]),json(p.headings||[]),json(p.tables||[]),json(p.links||[]),json(p.images||[]),p.ocr_used?'SI':'NO'];const ps=chunks(String(p.text||''));const pageRows=ps.map((part,i)=>{const r=[...row];r[3]=i+1;r[4]=ps.length;r[5]=part;return r;});await appendRowsSafe(id,'PAGINAS!A1',pageRows,'PAGINAS',driveId,name,p.page,`${driveId}:p${p.page}`);}}
async function appendRowsSafe(id:string,range:string,rowsIn:any[][],origin:string,docId:string,docName:string,page:number|string,stablePrefix:string){if(!rowsIn.length)return;const safe=rowsIn.map(r=>[...r]);const parts:any[][]=[];for(let r=0;r<safe.length;r++){for(let i=0;i<safe[r].length;i++){const v=safe[r][i];if(typeof v!=='string'||v.length<=CELL_LIMIT)continue;const ps=chunks(v),key=`${stablePrefix}:r${r}:c${i}`;for(let n=0;n<ps.length;n++)parts.push([docId,docName,origin,key,range.split('!')[0],page,n+1,ps.length,ps[n]]);safe[r][i]=`[ND_TEXT_PARTES key=${key} partes=${ps.length}]`;}}if(parts.length)await appendBatch(id,'ND_TEXT_PARTES!A1',parts);await appendBatch(id,range,safe);}
async function appendFindingRows(id:string,origin:string,docId:string,name:string,findings:NDFinding[],tab:string){if(findings.length)await appendRowsSafe(id,`${tab}!A1`,rows(name,docId,findings),origin,docId,name,findings[0].page,`${docId}:${origin}`);}
export async function appendFindings(id:string,driveId:string,name:string,findings:NDFinding[]){if(!findings.length)return;const normalized:NDFinding[]=findings.map(h=>{const kind=normalizeKind(h.kind);return kind?{...h,kind}:h;});await appendFindingRows(id,'HALLAZGOS_RAW',driveId,name,normalized,'HALLAZGOS_RAW');for(const kind of Object.keys(KIND_TO_TAB) as NDKind[]){const tab=KIND_TO_TAB[kind],subset=normalized.filter(x=>x.kind===kind);if(subset.length)await appendFindingRows(id,tab,driveId,name,subset,tab);}await appendRowsSafe(id,'Hoja 1!A1',normalized.map(h=>unifiedRow(name,h)),'Hoja 1',driveId,name,normalized[0].page,`${driveId}:unified`);}
export async function setDocumentStatus(id:string,driveId:string,name:string,status:string,total:number){await sheetsWrite(()=>sheets.spreadsheets.values.update({spreadsheetId:id,range:'DOCUMENTO!A2:D2',valueInputOption:'RAW',requestBody:{values:[[driveId,name,status,total]]}}));}
