import { google } from 'googleapis';
import type { NDFinding } from './types';

const TABS=['DOCUMENTO','HALLAZGOS_RAW','MATERIALES','COMPONENTES','PROPIEDADES','MAGNITUDES','ATRIBUTOS','RELACIONES','CONDICIONES','METODOS','INSTRUMENTOS','APLICACIONES','COMPORTAMIENTOS','NORMAS','DEFINICIONES','EVIDENCIAS','FORMULAS','ENTIDADES_DOCUMENTALES'];
const HEAD=['drive_id','documento','tipo','campo','entidad','aspecto','dato_documental','texto_original','texto_normalizado','valor','valor_texto','unidad','simbolo','contexto','pagina','seccion','confianza','evidencia_json','metadatos_json'];
function getAuth(){const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Falta GOOGLE_SERVICE_ACCOUNT_JSON');const c=JSON.parse(raw);return new google.auth.GoogleAuth({credentials:{client_email:c.client_email,private_key:c.private_key},scopes:['https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/spreadsheets']});}
const auth=getAuth(); const sheets=google.sheets({version:'v4',auth}); const drive=google.drive({version:'v3',auth});
async function ensure(id:string){const m=await sheets.spreadsheets.get({spreadsheetId:id,fields:'sheets.properties'});const have=new Set((m.data.sheets||[]).map(s=>s.properties?.title));const requests=TABS.filter(t=>!have.has(t)).map(t=>({addSheet:{properties:{title:t}}}));if(requests.length)await sheets.spreadsheets.batchUpdate({spreadsheetId:id,requestBody:{requests}});const data:any[]=[];for(const t of TABS){const r=await sheets.spreadsheets.values.get({spreadsheetId:id,range:`${t}!A1:S1`});if(!r.data.values?.length)data.push({range:`${t}!A1`,values:[t==='DOCUMENTO'?['drive_id','documento','estado','hallazgos_total']:HEAD]});}if(data.length)await sheets.spreadsheets.values.batchUpdate({spreadsheetId:id,requestBody:{valueInputOption:'RAW',data}});}
export async function createSheet(doc:NDFinding[],driveId:string,name:string){const parent=process.env.ND_SHEETS_FOLDER_ID;const r=await sheets.spreadsheets.create({requestBody:{properties:{title:`ARKON_ND_${name.replace(/[^\w.-]+/g,'_').slice(0,70)}`}}});const id=r.data.spreadsheetId!;await ensure(id);await sheets.spreadsheets.values.update({spreadsheetId:id,range:'DOCUMENTO!A2:D2',valueInputOption:'RAW',requestBody:{values:[[driveId,name,'completado',doc.length]]}});if(!doc.length)return id;const rows=doc.map(h=>[driveId,name,h.kind,h.field,h.entity,h.aspect,h.documentaryData,h.originalText,h.normalizedText,h.value??'',h.valueText??'',h.unit??'',h.symbol??'',h.context,h.page,h.section??'',h.confidence,JSON.stringify(h.evidence),JSON.stringify(h.metadata||{})]);await sheets.spreadsheets.values.batchUpdate({spreadsheetId:id,requestBody:{valueInputOption:'RAW',data:[{range:'HALLAZGOS_RAW!A:S',values:rows}]}});const map:any={MATERIAL:'MATERIALES',COMPONENTE:'COMPONENTES',PROPIEDAD:'PROPIEDADES',MAGNITUD:'MAGNITUDES',ATRIBUTO:'ATRIBUTOS',RELACION:'RELACIONES',CONDICION:'CONDICIONES',METODO:'METODOS',INSTRUMENTO:'INSTRUMENTOS',APLICACION:'APLICACIONES',COMPORTAMIENTO:'COMPORTAMIENTOS',NORMA:'NORMAS',DEFINICION:'DEFINICIONES',EVIDENCIA:'EVIDENCIAS',FORMULA:'FORMULAS',ENTIDAD:'ENTIDADES_DOCUMENTALES'};for(const [kind,tab] of Object.entries(map)){const rs=doc.filter(x=>x.kind===kind);if(rs.length)await sheets.spreadsheets.values.append({spreadsheetId:id,range:`${tab}!A:S`,valueInputOption:'RAW',requestBody:{values:rs.map(h=>[driveId,name,h.kind,h.field,h.entity,h.aspect,h.documentaryData,h.originalText,h.normalizedText,h.value??'',h.valueText??'',h.unit??'',h.symbol??'',h.context,h.page,h.section??'',h.confidence,JSON.stringify(h.evidence),JSON.stringify(h.metadata||{})])}});}
if(parent){await drive.files.update({fileId:id,addParents:parent,fields:'id,parents'});}return id;}
